### PR TITLE
Swiftly api

### PR DESCRIPTION
**Pull request by matikin9**

### CODE REVIEW

**Comment by albertkun** [comment]
Testing of the docker file has signified an error with the JSON not being found on line 103:
```
  File "/code/./app/main.py", line 103, in get_canceled_trip_summary

    with open(PATH_TO_CANCELED_JSON, 'r') as file:

FileNotFoundError: [Errno 2] No such file or directory: 'app/data/CancelledTripsRT.json'
```

Please test and send back with the `.json` file being read before the application hits the API.

**Review by albertkun — CHANGES_REQUESTED** [review]
Please fix the JSON request on line 103 of `main.py`

**Comment by matikin9** [comment]
> Please fix the JSON request on line 103 of `main.py`

@albertkun - code added to check for canceled trips file being non-existent or empty.  tested locally and with locally running docker container.

**Comment by albertkun** [comment]
Looks good!

**Pull request merged**
